-- 업그레이드 된 아이템 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/273711
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM (
  SELECT T.ITEM_ID
  FROM ITEM_TREE AS T
  JOIN ITEM_INFO AS I
  ON T.PARENT_ITEM_ID = I.ITEM_ID
  WHERE I.RARITY = "RARE") AS TARGET
JOIN ITEM_INFO AS INFO
ON TARGET.ITEM_ID = INFO.ITEM_ID
ORDER BY INFO.ITEM_ID DESC;